const pxToRem = (num) => `${num / 16}rem`;

module.exports = {
  mode: "jit",
  purge: [
    "./src/pages/**/*.{js,ts,jsx,tsx}",
    "./src/components/**/*.{js,ts,jsx,tsx}",
    "./safelist.txt",
  ],
  darkMode: "media",
  theme: {
    screens: {
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      xxl: "1640px",
      display: "2100px",
    },
    colors: {
      transparent: "transparent",
      current: "currentColor",
      white: "#ffffff",
      offwhite: "#FBFAF6",
      offwhiteRGB: "251, 250, 246",
      black: "#0D0D0D",
      blackRGB: "13,13,13",
      lightBlack: "#1D1D1D",
      blue: "#2400FF",
      orange: "#FF9900",
      pink: "#FF008A",
      "th-bg": "var(--bg)",
      "th-bg-opaq": "var(--bg-opaq)",
      "th-body": "var(--body)",
      "th-on-bg": "var(--on-bg)",
      "th-bg-inverted": "var(--bg-inverted)",
      "th-bg-inverted-opaq": "var(--bg-inverted-opaq)",
      "th-body-inverted": "var(--body-inverted)",
      // button context
      "th-btn-prim-front": "var(--btn-prim-front)",
      "th-btn-prim-bg": "var(--btn-prim-bg)",
      "th-btn-prim-bg-hover": "var(--btn-prim-bg-hover)",
      // Banner
      "th-banner-bg": "var(--banner-bg)",
      "th-banner-on-bg": "var(--banner-on-bg)",
    },
    fontSize: {
      10: [pxToRem(10), pxToRem(14)],
      14: [pxToRem(14), pxToRem(18)],
      16: [pxToRem(16), pxToRem(22)],
      20: [pxToRem(20), pxToRem(30)],
      24: [pxToRem(24), pxToRem(32)],
      32: [pxToRem(32), 1.2],
      40: [pxToRem(40), 1.2],
      48: [pxToRem(48), 1.2],
      50: [pxToRem(50), pxToRem(58)],
      62: [pxToRem(62), pxToRem(72)],
      64: [pxToRem(64), 1.2],
      80: [pxToRem(80), 1.2],
      96: [pxToRem(96), 1.2],
      102: [pxToRem(102), pxToRem(122)],
      120: [pxToRem(120), 1],
    },
    lineHeight: {
      none: "1",
      tight: "1.2",
      snug: "1.3",
      normal: "1.375",
      relaxed: "1.5",
      loose: "2",
    },
    extend: {
      fontFamily: {
        sans: "strawford, sans-serif",
      },
      spacing: {
        15: [pxToRem(60)],
        18: [pxToRem(72)],
        sm: [pxToRem(16)],
        md: [pxToRem(40)],
        lg: [pxToRem(64)],
        xl: [pxToRem(96)],
        xxl: [pxToRem(128)],
        xxxl: [pxToRem(192)],
        "section-gap": [pxToRem(96)],
        // push a column in flex-grid to the right by using these as margin left
        "0/12": "0%",
        "1/12": `${(100 / 12) * 1}%`,
        "2/12": `${(100 / 12) * 2}%`,
        "3/12": "25%",
        "4/12": `${(100 / 12) * 4}%`,
        "5/12": `${(100 / 12) * 5}%`,
        "6/12": "50%",
        "7/12": `${(100 / 12) * 7}%`,
        "8/12": `${(100 / 12) * 8}%`,
        "9/12": "75%",
        "10/12": `${(100 / 12) * 10}%`,
        "11/12": `${(100 / 12) * 11}%`,
        "12/12": "100%",
      },
      maxWidth: {
        page: "calc(1640px + 6rem - 20px)",
      },
      keyframes: {
        slideDown: {
          "0%": {
            transform: "scaleY(0)",
          },
          "100%": {
            transform: "scaleY(1)",
          },
        },
        slideUp: {
          "0%": {
            transition: "max-height",
            // transform: "scaleY(1)",
            "max-height": "10vw",
          },
          "100%": {
            // transform: "scaleY(0)",
            "max-height": 0,
          },
        },
        pullupMedia: {
          "0%": {
            transform: "translateY(25%)",
          },
          "100%": {
            transform: "translateY(0)",
          },
        },
      },
      animation: {
        slideDown: "slideDown 0.4s ease-in 1s forwards",
        slideUp: "slideUp 0.4s ease-in 0.4s forwards",
        "pullup-media": "pullupMedia 0.3s ease-out 1s forwards",
        clicked: "slideDown 0.4s ease-in 1s forwards",
      },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [
    // eslint-disable-next-line global-require
    require("tailwind-safelist-generator")({
      patterns: [
        "w-1/12",
        "{screens}:w-1/12",
        "w-2/12",
        "{screens}:w-2/12",
        "w-3/12",
        "{screens}:w-3/12",
        "w-4/12",
        "{screens}:w-4/12",
        "w-5/12",
        "{screens}:w-5/12",
        "w-6/12",
        "{screens}:w-6/12",
        "w-7/12",
        "{screens}:w-7/12",
        "w-8/12",
        "{screens}:w-8/12",
        "w-9/12",
        "{screens}:w-9/12",
        "w-10/12",
        "{screens}:w-10/12",
        "w-11/12",
        "{screens}:w-11/12",
        "w-full",
        "{screens}:w-full",
        // Push (for grids)
        "ml-0/12",
        "{screens}:ml-0/12",
        "ml-1/12",
        "{screens}:ml-1/12",
        "ml-2/12",
        "{screens}:ml-2/12",
        "ml-3/12",
        "{screens}:ml-3/12",
        "ml-4/12",
        "{screens}:ml-4/12",
        "ml-5/12",
        "{screens}:ml-5/12",
        "ml-6/12",
        "{screens}:ml-6/12",
        "ml-7/12",
        "{screens}:ml-7/12",
        "ml-8/12",
        "{screens}:ml-8/12",
        "ml-9/12",
        "{screens}:ml-9/12",
        "ml-10/12",
        "{screens}:ml-10/12",
        "ml-11/12",
        "{screens}:ml-11/12",
        "ml-12/12",
        "{screens}:ml-12/12",
        // function: use child selectors, eg. "child:m-10 child-hover:color-whatever"
        // ({ addVariant }) => {
        //   addVariant("child", "& > *");
        //   // addVariant("child-hover", "& > *:hover");
        // },
      ],
    }),
  ],
};
